"""Command-line entry point — milestones 1 through 7.

Exit codes:
    0  success
    1  config load/validation error
    2  run folder already exists (use --overwrite-run or --clean-run-folder)
    3  HYDRUS_EXE missing or invalid
    4  unsupported configuration feature for the adapter
    5  inputs/outputs missing
    6  runner pre-flight failure or timeout
    7  HYDRUS executed but failed (non-zero exit or false-success pattern,
       OR a hard step in --all failed)
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

from hydrus_agent import ConfigError, create_run_folder, load_config
from hydrus_agent.env import ENV_VAR, resolve_hydrus_exe


PROJECT_ROOT = Path(__file__).resolve().parent
DEFAULT_CONFIG = PROJECT_ROOT / "config" / "example_case.json"
RUNS_ROOT = PROJECT_ROOT / "runs"
REVIEW_STATE_DIR = PROJECT_ROOT / ".hydrus_agent_state"


def _build_parser() -> argparse.ArgumentParser:
    from hydrus_agent.runner import DEFAULT_LAUNCH_MODE, LAUNCH_MODES

    parser = argparse.ArgumentParser(
        prog="hydrus_agent",
        description="HYDRUS-1D agent CLI.",
    )
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG,
                        help=f"Path to model config JSON. Defaults to {DEFAULT_CONFIG}.")
    parser.add_argument("--prepare-input", action="store_true",
                        help="Write HYDRUS-1D input files via phydrus.")
    parser.add_argument("--run", action="store_true",
                        help="Invoke the HYDRUS-1D executable on the prepared inputs.")
    parser.add_argument("--diagnose-run", action="store_true",
                        help="Print a diagnostic report and exit 0 WITHOUT invoking HYDRUS.")
    parser.add_argument("--read-output", action="store_true",
                        help="Discover and parse HYDRUS output files; print a summary.")
    parser.add_argument("--plot", action="store_true",
                        help="Generate standard PNG figures into runs/<case_id>/figures/.")
    parser.add_argument("--qc", action="store_true",
                        help="Audit the run: write qc_summary.json under "
                             "runs/<case_id>/outputs/.")
    parser.add_argument("--report", action="store_true",
                        help="Write a Markdown report.md in the run folder.")
    parser.add_argument("--field-data", type=Path, default=None,
                        help="CSV or optional Excel field data to compare "
                             "against Obs_Node.out after outputs are read.")
    parser.add_argument("--scenario-file", type=Path, default=None,
                        help="Run a small scenario/sensitivity batch from "
                             "this scenario JSON file.")
    parser.add_argument("--scenario-report", type=Path, default=None,
                        help="Generate a comparison report from an existing "
                             "scenario batch directory.")
    parser.add_argument("--all", action="store_true",
                        help="Run the full pipeline end-to-end and write "
                             "pipeline_summary.json.")
    parser.add_argument("--benchmark-official", type=Path, default=None,
                        help="Run an official PC-Progress HYDRUS example "
                             "folder from an isolated benchmark copy.")
    parser.add_argument("--benchmark-manifest", type=Path, default=None,
                        help="Run supported official PC-Progress benchmark "
                             "cases from a manifest CSV.")
    parser.add_argument("--all-examples", action="store_true",
                        help="With --benchmark-manifest, run every official "
                             "example folder and write a full sweep report.")
    parser.add_argument("--benchmark-gap-report", type=Path, default=None,
                        help="Generate a benchmark gap-analysis report from "
                             "a manifest and the latest batch summary.")
    parser.add_argument("--benchmark-id", type=str, default=None,
                        help="Benchmark ID / result folder name for "
                             "--benchmark-official.")
    parser.add_argument("--describe", type=str, default=None,
                        help="Build a validated config JSON from a simple "
                             "natural-language model description. Does not "
                             "run HYDRUS.")
    parser.add_argument("--write-config", type=Path, default=None,
                        help="Where to write the config generated by "
                             "--describe.")
    parser.add_argument(
        "--write-config-template",
        metavar="PATH",
        nargs="?",
        default=None,
        const="__STDOUT__",
        help="Write the canonical LLM config template. Omit PATH to print "
             "to stdout, or supply a path to write the file there.",
    )
    parser.add_argument(
        "--print-config-schema",
        action="store_true",
        help="Print the JSON schema for ModelConfig and exit. "
             "Use --schema-output to write to a file instead.",
    )
    parser.add_argument(
        "--schema-output",
        type=Path,
        default=None,
        help="Write --print-config-schema output to this file.",
    )
    parser.add_argument("--science-review", action="store_true",
                        help="Run the deterministic scientific reviewer "
                             "against --config and print a markdown summary. "
                             "Does not run HYDRUS, does not modify review "
                             "state, and always exits 0 even when critical "
                             "items are present.")
    parser.add_argument("--review", action="store_true",
                        help="With --describe, print the generated config "
                             "summary and validation status before stopping.")
    parser.add_argument("--run-after-review", action="store_true",
                        help="With --describe, write and review the generated "
                             "config, then explicitly run the full pipeline "
                             "from that config.")
    parser.add_argument("--allow-config-mismatch", action="store_true",
                        help="Allow --all to run a config that differs from "
                             "the last reviewed generated config.")
    parser.add_argument("--overwrite-run", action="store_true",
                        help="Reuse existing run folder in place.")
    parser.add_argument("--clean-run-folder", action="store_true",
                        help="Recursively remove runs/<case_id>/ before recreating.")
    parser.add_argument("--timeout", type=float, default=None,
                        help="Wall-clock seconds before HYDRUS is killed.")
    parser.add_argument(
        "--hydrus-launch-mode",
        choices=list(LAUNCH_MODES),
        default=DEFAULT_LAUNCH_MODE,
        help=("How to invoke H1D_CALC.EXE. 'argv' (default) passes the project "
              "path as argv[1]. 'level-dir' relies on LEVEL_01.DIR in cwd."),
    )
    return parser


def _run_science_review_cli(config_path: Path) -> int:
    """Run the deterministic scientific reviewer and print a markdown
    summary. Never runs HYDRUS, never modifies review state, never
    requires prior review, and always returns 0."""
    try:
        config = load_config(config_path)
    except ConfigError as exc:
        print(f"[ERROR] Config did not load: {exc}", file=sys.stderr)
        # Even on a load error we exit 0: the reviewer is advisory only.
        return 0
    from hydrus_agent.scientific_reviewer import render_markdown, review_config
    result = review_config(config)
    print(render_markdown(result))
    return 0


def main(argv=None) -> int:
    args = _build_parser().parse_args(argv)

    if args.science_review:
        return _run_science_review_cli(args.config)

    if args.benchmark_gap_report is not None:
        if args.benchmark_manifest is not None or args.benchmark_official is not None:
            print("[ERROR] Use --benchmark-gap-report by itself, not with "
                  "--benchmark-manifest or --benchmark-official.", file=sys.stderr)
            return 1
        if args.benchmark_id is not None:
            print("[ERROR] --benchmark-id requires --benchmark-official.", file=sys.stderr)
            return 1
        return _run_benchmark_gap_report_cli(args.benchmark_gap_report)

    if args.scenario_report is not None:
        if args.scenario_file is not None:
            print("[ERROR] Use either --scenario-report or --scenario-file, "
                  "not both.", file=sys.stderr)
            return 1
        if args.benchmark_manifest is not None or args.benchmark_official is not None:
            print("[ERROR] Use --scenario-report by itself, not with benchmark "
                  "commands.", file=sys.stderr)
            return 1
        return _run_scenario_report_cli(args.scenario_report)

    if args.benchmark_manifest is not None:
        if args.benchmark_official is not None:
            print("[ERROR] Use either --benchmark-manifest or --benchmark-official, "
                  "not both.", file=sys.stderr)
            return 1
        if args.benchmark_id is not None:
            print("[ERROR] --benchmark-id requires --benchmark-official.", file=sys.stderr)
            return 1
        if args.all_examples:
            return _run_full_example_sweep_cli(
                args.benchmark_manifest,
                timeout=args.timeout,
                launch_mode=args.hydrus_launch_mode,
            )
        return _run_benchmark_manifest_cli(
            args.benchmark_manifest,
            timeout=args.timeout,
            launch_mode=args.hydrus_launch_mode,
        )

    if args.benchmark_official is not None:
        return _run_official_benchmark_cli(
            args.benchmark_official,
            args.benchmark_id,
            timeout=args.timeout,
            launch_mode=args.hydrus_launch_mode,
        )

    if args.write_config_template is not None:
        dest = None if args.write_config_template == "__STDOUT__" else Path(args.write_config_template)
        return _write_config_template_cli(dest)

    if args.print_config_schema:
        return _print_config_schema_cli(args.schema_output)

    if args.describe is not None:
        return _describe_config(
            args.describe,
            args.write_config,
            review=args.review,
            run_after_review=args.run_after_review,
            overwrite_run=args.overwrite_run,
            timeout=args.timeout,
            launch_mode=args.hydrus_launch_mode,
            allow_config_mismatch=args.allow_config_mismatch,
            field_data_path=args.field_data,
        )

    if args.write_config is not None:
        print("[ERROR] --write-config requires --describe.", file=sys.stderr)
        return 1
    if args.all_examples:
        print("[ERROR] --all-examples requires --benchmark-manifest.", file=sys.stderr)
        return 1
    if args.review:
        return _review_existing_config(args.config)
    if args.run_after_review:
        print("[ERROR] --run-after-review requires --describe.", file=sys.stderr)
        return 1
    if args.benchmark_id is not None:
        print("[ERROR] --benchmark-id requires --benchmark-official.", file=sys.stderr)
        return 1

    if args.scenario_file is not None:
        return _run_scenario_batch_cli(
            args.config,
            args.scenario_file,
            timeout=args.timeout,
            launch_mode=args.hydrus_launch_mode,
            field_data_path=args.field_data,
            overwrite_run=True,
        )

    if args.all:
        if not args.allow_config_mismatch:
            rc = _check_review_consistency(args.config)
            if rc != 0:
                return rc
        return _call_run_all(
            args.config,
            overwrite_run=args.overwrite_run,
            timeout=args.timeout,
            launch_mode=args.hydrus_launch_mode,
            field_data_path=args.field_data,
        )

    print(f"Loading config: {args.config}")
    try:
        config = load_config(args.config)
    except ConfigError as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        return 1

    print(f"  project_name : {config.project_name}")
    print(f"  case_id      : {config.case_id}")
    print(f"  sim window   : {config.simulation_time.t_init} to "
          f"{config.simulation_time.t_end} {config.simulation_time.units.value}")
    print(f"  soil layers  : {len(config.soil_profile)}")
    print(f"  obs depths   : {config.observation_depths}")

    case_dir = RUNS_ROOT / config.case_id

    if args.diagnose_run:
        return _diagnose_run(case_dir, launch_mode=args.hydrus_launch_mode)
    if args.read_output:
        return _read_output(case_dir, field_data_path=args.field_data, config=config)
    if args.plot:
        return _plot(case_dir, field_data_path=args.field_data, config=config)
    if args.qc:
        return _qc(case_dir, field_data_path=args.field_data, config=config)
    if args.report:
        return _report(config, case_dir, field_data_path=args.field_data)

    if args.clean_run_folder:
        _safe_clean(case_dir)

    try:
        case_dir = create_run_folder(config, runs_root=RUNS_ROOT,
                                     overwrite=args.overwrite_run)
    except FileExistsError as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        print("        Pass --overwrite-run to reuse in place, or "
              "--clean-run-folder to start from scratch.", file=sys.stderr)
        return 2

    print(f"Run folder: {case_dir}")

    if args.prepare_input:
        rc = _prepare_input(config, case_dir)
        if rc != 0:
            return rc

    if args.run:
        return _run(case_dir, timeout=args.timeout,
                    launch_mode=args.hydrus_launch_mode)
    return 0


def _write_config_template_cli(dest=None) -> int:
    """Write the canonical LLM config template to *dest* or stdout."""
    template_path = PROJECT_ROOT / "config" / "templates" / "llm_config_template.json"
    if not template_path.is_file():
        print(f"[ERROR] Template not found: {template_path}", file=sys.stderr)
        return 1
    content = template_path.read_text(encoding="utf-8")
    if dest is None:
        print(content)
    else:
        dest = Path(dest)
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")
        print(f"Template written to: {dest}")
    return 0


def _print_config_schema_cli(output=None) -> int:
    """Print the JSON schema for ModelConfig."""
    from hydrus_agent.schema import ModelConfig
    schema_text = json.dumps(ModelConfig.model_json_schema(), indent=2)
    if output is not None:
        output = Path(output)
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(schema_text, encoding="utf-8")
        print(f"Schema written to: {output}")
    else:
        print(schema_text)
    return 0


def _safe_clean(case_dir: Path) -> None:
    case_dir = case_dir.resolve()
    runs_root = RUNS_ROOT.resolve()
    try:
        case_dir.relative_to(runs_root)
    except ValueError:
        raise SystemExit(f"[FATAL] Refusing to clean {case_dir}: not under {runs_root}.")
    if case_dir == runs_root:
        raise SystemExit(f"[FATAL] Refusing to clean the runs root itself: {case_dir}.")
    if case_dir.exists():
        print(f"Cleaning existing run folder: {case_dir}")
        shutil.rmtree(case_dir)


def _prepare_input(config, case_dir: Path) -> int:
    exe_str, source = resolve_hydrus_exe()
    if exe_str is None:
        print(f"[ERROR] {ENV_VAR} is not set; required for --prepare-input.", file=sys.stderr)
        return 3
    exe_path = Path(exe_str)
    if not exe_path.is_file():
        print(f"[ERROR] HYDRUS executable not found at {exe_path} (from {source}).",
              file=sys.stderr)
        return 3

    from hydrus_agent.phydrus_adapter import (
        UnsupportedFeatureError, prepare_phydrus_project,
    )
    try:
        project_dir = prepare_phydrus_project(config, case_dir, exe_path)
    except UnsupportedFeatureError as exc:
        print(f"[ERROR] Configuration not yet supported: {exc}", file=sys.stderr)
        return 4

    print(f"HYDRUS input files written to: {project_dir}")
    for f in sorted(project_dir.iterdir()):
        print(f"  - {f.name}")
    return 0


def _run(case_dir: Path, *, timeout=None, launch_mode="argv") -> int:
    project_dir = case_dir / "hydrus_project"
    log_dir = case_dir / "logs"

    if not (project_dir / "SELECTOR.IN").is_file():
        print(f"[ERROR] No HYDRUS inputs found in {project_dir}. "
              "Pass --prepare-input first (or alongside --run).", file=sys.stderr)
        return 5

    exe_str, source = resolve_hydrus_exe()
    if exe_str is None:
        print(f"[ERROR] {ENV_VAR} is not set; required for --run.", file=sys.stderr)
        return 3
    exe_path = Path(exe_str)
    if not exe_path.is_file():
        print(f"[ERROR] HYDRUS executable not found at {exe_path} (from {source}).",
              file=sys.stderr)
        return 3

    from hydrus_agent.runner import RunnerError, run_hydrus_project

    print(f"Invoking HYDRUS: {exe_path}")
    print(f"  launch mode : {launch_mode}")
    print(f"  cwd         : {project_dir}")
    if timeout is not None:
        print(f"  timeout     : {timeout}s")
    try:
        result = run_hydrus_project(project_dir, exe_path, log_dir,
                                    timeout=timeout, launch_mode=launch_mode)
    except RunnerError as exc:
        print(f"[ERROR] Runner failed: {exc}", file=sys.stderr)
        print("        Run main.py --diagnose-run for a full diagnostic report.",
              file=sys.stderr)
        return 6

    print(f"HYDRUS finished with return code {result.return_code}")
    print(f"Command run : {result.cmd}")
    print(f"Log: {result.log_path}")
    if result.generated_files:
        print("Generated files:")
        for f in result.generated_files:
            print(f"  - {f.name}")
    else:
        print("No new files were written by HYDRUS in the project directory.")

    if result.false_success_reason:
        print(f"[ERROR] HYDRUS exited 0 but output contained the failure marker "
              f"'{result.false_success_reason}'. Treating as failure. "
              f"See {result.log_path} for details.", file=sys.stderr)
        return 7
    if not result.success:
        print(f"[ERROR] HYDRUS exited with non-zero return code "
              f"{result.return_code}. See {result.log_path} for details.",
              file=sys.stderr)
        return 7
    return 0


def _read_output(case_dir: Path, *, field_data_path: Path | None = None, config=None) -> int:
    project_dir = case_dir / "hydrus_project"
    if not project_dir.is_dir():
        print(f"[ERROR] Project directory does not exist: {project_dir}",
              file=sys.stderr)
        return 5

    from hydrus_agent.output_reader import (
        DEFAULT_OUTPUT_NAMES, summarise_outputs,
    )

    print()
    print(f"HYDRUS-1D output summary for {case_dir.name}")
    print("=" * 60)
    print(f"Project directory: {project_dir}")
    print()
    summary = summarise_outputs(project_dir, DEFAULT_OUTPUT_NAMES)
    found_any_data = False
    for entry in summary:
        if not entry["found"]:
            print(f"  {entry['name']:<14} : not found")
            continue
        size = entry["size_bytes"]
        rows = entry["rows"]
        cols = entry["columns"]
        if size == 0 or rows == 0:
            print(f"  {entry['name']:<14} : found ({size} bytes) — empty / no parsed rows")
        else:
            found_any_data = True
            cols_preview = ", ".join(entry["first_columns"]) or "(no columns)"
            print(f"  {entry['name']:<14} : found ({size} bytes), {rows} rows × {cols} cols")
            print(f"                   first columns: {cols_preview}")
    print()
    print("=" * 60)
    if not found_any_data:
        print("All discovered files are empty or missing.")
    else:
        print("Done. Source files were not modified.")
    if field_data_path is not None:
        from hydrus_agent.output_reader import read_outputs
        outputs = read_outputs(project_dir)
        summary, figures, summary_path = _run_field_comparison_for_case(
            outputs, field_data_path, config, case_dir,
        )
        print(f"Field comparison summary saved to: {summary_path}")
        print(f"Matched field rows: {summary.get('matched_rows', 0)}")
        if figures:
            print("Field overlay figures:")
            for figure in figures:
                print(f"  - {figure}")
    return 0


def _plot(case_dir: Path, *, field_data_path: Path | None = None, config=None) -> int:
    project_dir = case_dir / "hydrus_project"
    figure_dir = case_dir / "figures"
    if not project_dir.is_dir():
        print(f"[ERROR] Project directory does not exist: {project_dir}",
              file=sys.stderr)
        return 5
    from hydrus_agent.output_reader import read_outputs
    from hydrus_agent.plotter import generate_standard_plots

    print()
    print(f"HYDRUS-1D plotting for {case_dir.name}")
    print("=" * 60)
    print(f"Source dir : {project_dir}")
    print(f"Figure dir : {figure_dir}")
    outputs = read_outputs(project_dir)
    figures = generate_standard_plots(outputs, figure_dir)
    print()
    if not figures:
        print("No figures were created. The output DataFrames were missing or empty.")
    else:
        print(f"Created {len(figures)} figure(s):")
        for f in figures:
            print(f"  - {f}")
    if field_data_path is not None:
        summary, field_figures, summary_path = _run_field_comparison_for_case(
            outputs, field_data_path, config, case_dir,
        )
        print(f"Field comparison summary saved to: {summary_path}")
        for f in field_figures:
            print(f"  - {f}")
    return 0


def _qc(case_dir: Path, *, field_data_path: Path | None = None, config=None) -> int:
    project_dir = case_dir / "hydrus_project"
    figure_dir = case_dir / "figures"
    outputs_dir = case_dir / "outputs"
    if not project_dir.is_dir():
        print(f"[ERROR] Project directory does not exist: {project_dir}",
              file=sys.stderr)
        return 5

    from hydrus_agent.output_reader import read_outputs
    from hydrus_agent.qc import (
        assess_run_quality, format_qc_summary, write_qc_summary,
    )

    outputs = read_outputs(project_dir)
    figures = sorted(figure_dir.glob("*.png")) if figure_dir.is_dir() else []
    field_summary = None
    if field_data_path is not None:
        field_summary, field_figures, field_summary_path = _run_field_comparison_for_case(
            outputs, field_data_path, config, case_dir,
        )
        figures = sorted({*figures, *field_figures}, key=str)
    report = assess_run_quality(
        outputs, figures=figures, field_comparison=field_summary,
    )

    print()
    print(f"HYDRUS-1D run quality assessment for {case_dir.name}")
    print("=" * 60)
    print(format_qc_summary(report))
    print("=" * 60)
    qc_path = outputs_dir / "qc_summary.json"
    write_qc_summary(report, qc_path)
    print(f"\nQC summary saved to: {qc_path}")
    if field_data_path is not None:
        print(f"Field comparison summary saved to: {field_summary_path}")
    return 0


def _report(config, case_dir: Path, *, field_data_path: Path | None = None) -> int:
    import json

    project_dir = case_dir / "hydrus_project"
    outputs_dir = case_dir / "outputs"
    figure_dir = case_dir / "figures"
    if not project_dir.is_dir():
        print(f"[ERROR] Project directory does not exist: {project_dir}",
              file=sys.stderr)
        return 5

    from hydrus_agent.output_reader import read_outputs
    from hydrus_agent.plotter import generate_standard_plots
    from hydrus_agent.qc import assess_run_quality, write_qc_summary
    from hydrus_agent.reporter import generate_markdown_report

    print()
    print(f"HYDRUS-1D report for {case_dir.name}")
    print("=" * 60)
    outputs = read_outputs(project_dir)

    existing_figures = sorted(figure_dir.glob("*.png")) if figure_dir.is_dir() else []
    if existing_figures:
        print(f"Using {len(existing_figures)} existing figure(s) from {figure_dir}")
        figures = existing_figures
    else:
        print(f"No existing figures; generating into {figure_dir}")
        figures = generate_standard_plots(outputs, figure_dir)

    field_summary = None
    if field_data_path is not None:
        field_summary, field_figures, field_summary_path = _run_field_comparison_for_case(
            outputs, field_data_path, config, case_dir,
        )
        figures = sorted({*figures, *field_figures}, key=str)
        print(f"Field comparison summary saved to: {field_summary_path}")

    qc_path = outputs_dir / "qc_summary.json"
    if qc_path.is_file():
        print(f"Reusing existing QC summary: {qc_path}")
        qc_summary = json.loads(qc_path.read_text(encoding="utf-8"))
        if field_summary is not None:
            qc_summary = assess_run_quality(
                outputs, figures=figures, field_comparison=field_summary,
            )
            write_qc_summary(qc_summary, qc_path)
    else:
        print(f"Generating QC summary at {qc_path}")
        qc_summary = assess_run_quality(
            outputs, figures=figures, field_comparison=field_summary,
        )
        write_qc_summary(qc_summary, qc_path)

    report_path = generate_markdown_report(
        config, case_dir, outputs, qc_summary, figures,
    )
    print(f"Report written to: {report_path}")
    return 0


def _run_all(
    config_path: Path,
    *,
    overwrite_run: bool,
    timeout,
    launch_mode: str,
    field_data_path: Path | None = None,
) -> int:
    from hydrus_agent.pipeline import run_full_pipeline

    print()
    print("HYDRUS-1D full pipeline")
    print("=" * 60)
    print(f"config       : {config_path}")
    print(f"launch mode  : {launch_mode}")
    print(f"overwrite    : {overwrite_run}")
    if timeout is not None:
        print(f"timeout      : {timeout}s")
    if field_data_path is not None:
        print(f"field data   : {field_data_path}")

    summary = run_full_pipeline(
        config_path, overwrite_run=overwrite_run, timeout=timeout,
        hydrus_launch_mode=launch_mode,
        field_data_path=field_data_path,
    )

    print()
    for step in summary["steps"]:
        flag = "OK  " if step["ok"] else "FAIL"
        print(f"  [{flag}] {step['step']}")
        for w in step.get("warnings", []):
            print(f"         warning: {w}")
        if step.get("error"):
            print(f"         error  : {step['error']}")
    print()
    print("=" * 60)
    if summary["ok"]:
        print(f"Pipeline succeeded. Run folder: {summary.get('run_dir')}")
    else:
        stopped = summary.get("stopped_after_step")
        if stopped:
            print(f"Pipeline failed. Stopped after step: {stopped}")
        else:
            print("Pipeline finished with warnings/failures in soft steps.")
    hydrus_status = summary.get("hydrus_status", {})
    if hydrus_status.get("numerical_failure_detected"):
        print(
            "HYDRUS returned code "
            f"{hydrus_status.get('return_code')}, but numerical failure "
            "was detected in Error.msg."
        )
        reason = hydrus_status.get("failure_reason")
        if reason:
            print(f"Numerical failure reason: {reason}")
        print("Results may be incomplete or unreliable.")
    if summary.get("qc_status") == "failed":
        print("QC status: failed.")
        print("Results may be incomplete or unreliable.")
    if summary.get("summary_path"):
        print(f"Summary JSON: {summary['summary_path']}")
    return 0 if summary["ok"] else 7


def _run_official_benchmark_cli(
    source_dir: Path,
    benchmark_id: str | None,
    *,
    timeout,
    launch_mode: str,
) -> int:
    if benchmark_id is None:
        print("[ERROR] --benchmark-official requires --benchmark-id.", file=sys.stderr)
        return 1

    from hydrus_agent.benchmark import run_official_benchmark

    print()
    print("HYDRUS-1D official benchmark")
    print("=" * 60)
    print(f"source       : {source_dir}")
    print(f"benchmark id : {benchmark_id}")
    print(f"launch mode  : {launch_mode}")
    if timeout is not None:
        print(f"timeout      : {timeout}s")

    summary = run_official_benchmark(
        source_dir,
        benchmark_id,
        timeout=timeout,
        hydrus_launch_mode=launch_mode,
    )

    print()
    print(f"Official benchmark: {summary.get('benchmark_id')}")
    print(f"Result folder     : {summary.get('run_dir')}")
    if summary.get("stopped_after_step"):
        print(f"Stopped after     : {summary['stopped_after_step']}")
    run_info = summary.get("run", {})
    if run_info.get("error"):
        print(f"Run error         : {run_info['error']}")
    print(f"Summary JSON      : {summary.get('summary_path')}")
    return 0 if summary.get("ok") else 7


def _run_benchmark_manifest_cli(
    manifest_path: Path,
    *,
    timeout,
    launch_mode: str,
) -> int:
    from hydrus_agent.benchmark import run_benchmark_manifest

    effective_timeout = 60 if timeout is None else timeout

    print()
    print("HYDRUS-1D official benchmark batch")
    print("=" * 60)
    print(f"manifest     : {manifest_path}")
    print(f"launch mode  : {launch_mode}")
    print(f"timeout      : {effective_timeout}s")

    summary = run_benchmark_manifest(
        manifest_path,
        timeout=effective_timeout,
        hydrus_launch_mode=launch_mode,
        only_supported=True,
    )

    counts = summary.get("counts", {})
    print()
    print(
        "Results       : "
        f"pass={counts.get('pass', 0)}, "
        f"partial={counts.get('partial', 0)}, "
        f"fail={counts.get('fail', 0)}, "
        f"skipped={counts.get('skipped', 0)}"
    )
    print(f"Batch summary CSV : {summary.get('summary_csv_path')}")
    print(f"Batch summary JSON: {summary.get('summary_json_path')}")
    return 0 if summary.get("ok") else 7


def _run_full_example_sweep_cli(
    manifest_path: Path,
    *,
    timeout,
    launch_mode: str,
) -> int:
    from hydrus_agent.benchmark import run_full_example_sweep

    effective_timeout = 60 if timeout is None else timeout
    report_path = Path("docs") / "full_example_sweep_report.md"

    print()
    print("HYDRUS-1D full official example sweep")
    print("=" * 60)
    print(f"manifest     : {manifest_path}")
    print(f"launch mode  : {launch_mode}")
    print(f"timeout      : {effective_timeout}s")

    summary = run_full_example_sweep(
        manifest_path,
        examples_root=None,
        timeout=effective_timeout,
        hydrus_launch_mode=launch_mode,
        report_path=report_path,
    )

    counts = summary.get("counts", {})
    print()
    print(
        "Results       : "
        f"pass={counts.get('pass', 0)}, "
        f"partial={counts.get('partial', 0)}, "
        f"fail={counts.get('fail', 0)}, "
        f"skipped={counts.get('skipped', 0)}, "
        f"future={counts.get('future', 0)}"
    )
    print(f"Full sweep CSV : {summary.get('summary_csv_path')}")
    print(f"Full sweep JSON: {summary.get('summary_json_path')}")
    print(f"Full sweep report: {summary.get('report_path')}")
    return 0 if summary.get("ok") else 7


def _run_benchmark_gap_report_cli(manifest_path: Path) -> int:
    from hydrus_agent import benchmark as benchmark_module

    batch_summary_path = (
        benchmark_module.BENCHMARK_RESULTS_ROOT
        / benchmark_module.BATCH_SUMMARY_CSV_FILENAME
    )
    output_path = (
        benchmark_module.BENCHMARK_RESULTS_ROOT
        / benchmark_module.GAP_REPORT_FILENAME
    )

    print()
    print("HYDRUS-1D benchmark gap report")
    print("=" * 60)
    print(f"manifest      : {manifest_path}")
    print(f"batch summary : {batch_summary_path}")

    try:
        report_path = benchmark_module.generate_benchmark_gap_report(
            manifest_path,
            batch_summary_path,
            output_path,
        )
    except FileNotFoundError as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        return 1

    print(f"Gap report    : {report_path}")
    return 0


def _run_scenario_batch_cli(
    base_config_path: Path,
    scenario_file: Path,
    *,
    timeout,
    launch_mode: str,
    field_data_path: Path | None,
    overwrite_run: bool,
) -> int:
    from hydrus_agent.scenario_runner import ScenarioError, run_scenario_batch

    print()
    print("HYDRUS-1D scenario batch")
    print("=" * 60)
    print(f"base config  : {base_config_path}")
    print(f"scenario file: {scenario_file}")
    print(f"launch mode  : {launch_mode}")
    if timeout is not None:
        print(f"timeout      : {timeout}s")
    if field_data_path is not None:
        print(f"field data   : {field_data_path}")

    try:
        summary = run_scenario_batch(
            base_config_path,
            scenario_file,
            timeout=timeout,
            hydrus_launch_mode=launch_mode,
            field_data_path=field_data_path,
            overwrite_run=overwrite_run,
        )
    except ScenarioError as exc:
        print(f"[ERROR] Scenario batch failed: {exc}", file=sys.stderr)
        return 1

    counts = summary.get("counts", {})
    print()
    print(
        "Results       : "
        f"pass={counts.get('pass', 0)}, "
        f"fail={counts.get('fail', 0)}"
    )
    print(f"Scenario summary CSV : {summary.get('summary_csv_path')}")
    print(f"Scenario summary JSON: {summary.get('summary_json_path')}")
    return 0 if summary.get("ok") else 7


def _run_scenario_report_cli(batch_dir: Path) -> int:
    from hydrus_agent.scenario_analysis import (
        ScenarioAnalysisError,
        generate_scenario_comparison_report,
    )

    print()
    print("HYDRUS-1D scenario comparison report")
    print("=" * 60)
    print(f"batch dir    : {batch_dir}")

    try:
        report_path = generate_scenario_comparison_report(batch_dir)
    except ScenarioAnalysisError as exc:
        print(f"[ERROR] Scenario comparison failed: {exc}", file=sys.stderr)
        return 1

    print(f"Scenario report: {report_path}")
    return 0


def _describe_config(
    description: str,
    write_config_path: Path | None,
    *,
    review: bool = False,
    run_after_review: bool = False,
    overwrite_run: bool = False,
    timeout=None,
    launch_mode: str = "argv",
    allow_config_mismatch: bool = False,
    field_data_path: Path | None = None,
) -> int:
    if write_config_path is None:
        print("[ERROR] --describe requires --write-config <path>.", file=sys.stderr)
        return 1

    from hydrus_agent.config_builder import (
        ConfigBuildError,
        build_config_from_description,
        summarise_built_config,
        write_config,
    )

    case_id = write_config_path.stem or "from_description"
    try:
        result = build_config_from_description(description, case_id=case_id)
    except ConfigBuildError as exc:
        print(f"[ERROR] Could not build config: {exc}", file=sys.stderr)
        return 1

    path = write_config(result.config, write_config_path)
    if review or run_after_review:
        from hydrus_agent.review_state import write_review_state
        write_review_state(
            config=result.config,
            config_path=path,
            state_dir=REVIEW_STATE_DIR,
        )
    summary = summarise_built_config(result)
    if run_after_review:
        summary = summary.replace(
            "HYDRUS was not run.",
            "HYDRUS will run only because --run-after-review was provided.",
        )
    print(summary)
    if review or run_after_review:
        print("Validation status: valid ModelConfig")
    print(f"Config written to: {path}")
    if run_after_review:
        if not allow_config_mismatch:
            rc = _check_review_consistency(path)
            if rc != 0:
                return rc
        print("Running full pipeline from reviewed config.")
        return _call_run_all(
            path,
            overwrite_run=overwrite_run,
            timeout=timeout,
            launch_mode=launch_mode,
            field_data_path=field_data_path,
        )
    return 0


def _review_existing_config(config_path: Path) -> int:
    from hydrus_agent.review_state import write_review_state

    try:
        config = load_config(config_path)
    except ConfigError as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        return 1

    write_review_state(
        config=config,
        config_path=config_path,
        state_dir=REVIEW_STATE_DIR,
    )
    print(_format_config_review(config))
    print("Validation status: valid ModelConfig")
    print(f"Reviewed config: {config_path}")
    print("HYDRUS was not run.")
    return 0


def _format_config_review(config) -> str:
    ic = config.initial_condition
    if ic.profile:
        points = ", ".join(f"{p.value} m at {p.depth} m" for p in ic.profile)
        ic_line = f"  initial cond : {ic.type.value} profile ({points})"
    else:
        ic_line = f"  initial cond : {ic.type.value} = {ic.value}"

    lines = [
        "Reviewed HYDRUS-1D config",
        f"  project_name : {config.project_name}",
        f"  case_id      : {config.case_id}",
        f"  sim window   : {config.simulation_time.t_init} to "
        f"{config.simulation_time.t_end} {config.simulation_time.units.value}",
        f"  soil layers  : {len(config.soil_profile)}",
        f"  materials    : {len(config.van_genuchten)}",
        f"  upper BC     : {config.upper_boundary.type.value}",
        f"  lower BC     : {config.lower_boundary.type.value}",
        ic_line,
        f"  obs depths   : {config.observation_depths}",
        f"  print times  : {config.output_settings.print_times}",
    ]
    if config.atmospheric is not None and config.atmospheric.source_metadata is not None:
        meta = config.atmospheric.source_metadata
        path_kind = "absolute" if Path(meta.source_csv).is_absolute() else "relative"
        lines.extend([
            "  atmospheric CSV:",
            f"    path        : {meta.source_csv} ({path_kind})",
            f"    records     : {meta.record_count}",
            f"    time range  : {meta.time_range[0]} to {meta.time_range[1]} {meta.time_unit}",
            f"    total precip: {meta.total_precipitation} m",
            f"    total evap  : {meta.total_potential_evaporation} m",
            f"    max precip  : {meta.max_precipitation_rate} {meta.rate_unit}",
            f"    max evap    : {meta.max_potential_evaporation_rate} {meta.rate_unit}",
            f"    units       : time={meta.time_unit}, length={meta.length_unit}, rate={meta.rate_unit}",
            "    covers end  : "
            f"{'yes' if meta.covers_simulation_end_time else 'no'}",
        ])
    if config.material_source is not None:
        meta = config.material_source
        path_kind = "absolute" if Path(meta.source_csv).is_absolute() else "relative"
        lines.extend([
            "  material CSV:",
            f"    path        : {meta.source_csv} ({path_kind})",
            f"    materials   : {meta.material_count}",
            f"    names       : {', '.join(meta.material_names)}",
            "    units       : "
            f"theta={meta.theta_unit}, alpha={meta.alpha_unit}, "
            f"Ks={meta.ks_unit}, l={meta.l_unit}",
        ])
        for material in meta.materials:
            lines.append(
                "    "
                f"{material.material_id}: {material.name} "
                f"theta_r={material.theta_r} theta_s={material.theta_s} "
                f"alpha={material.alpha} {meta.alpha_unit} "
                f"n={material.n} Ks={material.Ks} {meta.ks_unit} "
                f"l={material.l}"
            )
    return "\n".join(lines)


def _call_run_all(
    config_path: Path,
    *,
    overwrite_run: bool,
    timeout,
    launch_mode: str,
    field_data_path: Path | None,
) -> int:
    if field_data_path is None:
        return _run_all(
            config_path,
            overwrite_run=overwrite_run,
            timeout=timeout,
            launch_mode=launch_mode,
        )
    return _run_all(
        config_path,
        overwrite_run=overwrite_run,
        timeout=timeout,
        launch_mode=launch_mode,
        field_data_path=field_data_path,
    )


def _run_field_comparison_for_case(outputs, field_data_path: Path, config, case_dir: Path):
    from hydrus_agent.field_comparison import run_field_comparison

    observation_depths = getattr(config, "observation_depths", None) if config is not None else None
    return run_field_comparison(
        outputs,
        field_data_path,
        output_dir=case_dir / "outputs",
        figure_dir=case_dir / "figures",
        observation_depths=observation_depths,
    )


def _check_review_consistency(config_path: Path) -> int:
    from hydrus_agent.review_state import (
        build_requested_state,
        format_state_summary,
        read_review_state,
        states_match,
    )

    reviewed = read_review_state(REVIEW_STATE_DIR)
    if reviewed is None:
        return 0

    try:
        requested_config = load_config(config_path)
    except ConfigError as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        return 1

    requested = build_requested_state(
        config=requested_config,
        config_path=config_path,
    )
    if states_match(reviewed, requested):
        return 0

    print("[ERROR] The config being run is not the last reviewed config.")
    print(format_state_summary("Last reviewed config", reviewed))
    print(format_state_summary("Requested config", requested))
    print("Pass --allow-config-mismatch to run this config anyway.")
    return 1


def _diagnose_run(case_dir: Path, *, launch_mode="argv") -> int:
    from hydrus_agent.runner import (
        LEVEL_01_DIR_FILENAME, TIMEOUT_MARKER, inventory_dir,
    )

    project_dir = case_dir / "hydrus_project"
    log_path = case_dir / "logs" / "hydrus_run.log"
    level_01_path = project_dir / LEVEL_01_DIR_FILENAME

    print()
    print("HYDRUS-1D run diagnostic")
    print("=" * 60)
    print(f"launch mode  : {launch_mode}")

    exe_str, source = resolve_hydrus_exe()
    if exe_str is None:
        print(f"HYDRUS_EXE   : <unset> (source: {source})")
    else:
        exe_path = Path(exe_str)
        print(f"HYDRUS_EXE   : {exe_path}")
        print(f"  source     : {source}")
        print(f"  exists     : {exe_path.exists()}")
        if exe_path.is_file():
            print(f"  size_bytes : {exe_path.stat().st_size}")
        if launch_mode == "argv":
            preview_cmd = [str(exe_path), str(project_dir.resolve()), "-1"]
        else:
            preview_cmd = [str(exe_path)]
        print(f"  would run  : {preview_cmd}")
        print(f"  cwd        : {project_dir}")

    print()
    print(f"Run folder   : {case_dir}")
    print(f"  exists     : {case_dir.exists()}")
    print(f"Project dir  : {project_dir}")
    print(f"  exists     : {project_dir.exists()}")

    selector = project_dir / "SELECTOR.IN"
    profile = project_dir / "PROFILE.DAT"
    print()
    sel_part = f" ({selector.stat().st_size} bytes)" if selector.is_file() else ""
    pro_part = f" ({profile.stat().st_size} bytes)" if profile.is_file() else ""
    print(f"SELECTOR.IN  : {'present' if selector.is_file() else 'MISSING'}{sel_part}")
    print(f"PROFILE.DAT  : {'present' if profile.is_file() else 'MISSING'}{pro_part}")
    if level_01_path.is_file():
        body = level_01_path.read_text(encoding="utf-8", errors="replace").rstrip()
        print(f"LEVEL_01.DIR : present ({level_01_path.stat().st_size} bytes)")
        print(f"  contents   : {body!r}")
    else:
        print("LEVEL_01.DIR : MISSING (will be auto-generated by --run)")

    print()
    print("Pre-run file inventory:")
    inventory = inventory_dir(project_dir)
    if not inventory:
        print("  (project dir is empty or missing)")
    else:
        for fi in inventory:
            print(fi.format_line())

    print()
    if log_path.is_file():
        log_text = log_path.read_text(encoding="utf-8", errors="replace")
        timed_out = TIMEOUT_MARKER in log_text
        print(f"Previous log : {log_path}")
        print(f"  size_bytes : {log_path.stat().st_size}")
        print(f"  timed out  : {timed_out}")
        print("  first lines:")
        for ln in log_text.splitlines()[:8]:
            print(f"    {ln}")
    else:
        print(f"Previous log : (none at {log_path})")

    print()
    print("=" * 60)
    print("Diagnostic complete. HYDRUS was NOT invoked.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
